#!/bin/bash
pushd lib
VERSION=$(python -c "import version; print version.ELECTRUM_VERSION")".0"
popd
echo $VERSION
echo "version_apk = '$VERSION'" > contrib/versions.py
pushd ./gui/kivy/
make theming
make release
popd
