#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_XUEZ_VERSION=${VERSION_STRING[2]}
ELECTRUM_XUEZ_VERSION=${ELECTRUM_XUEZ_VERSION#\'}
ELECTRUM_XUEZ_VERSION=${ELECTRUM_XUEZ_VERSION%\'}
DOTS=`echo $ELECTRUM_XUEZ_VERSION |  grep -o "\." | wc -l`
if [[ $DOTS -lt 3 ]]; then
    ELECTRUM_XUEZ_APK_VERSION=$ELECTRUM_XUEZ_VERSION.0
else
    ELECTRUM_XUEZ_APK_VERSION=$ELECTRUM_XUEZ_VERSION
fi
export ELECTRUM_XUEZ_VERSION
export ELECTRUM_XUEZ_APK_VERSION
